# linter の設定
linters:
  # 全ての linter を無効化
  disable-all: true
  # 指定した linter のみ有効化
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - varcheck
    - misspell
    - lll
    - gofumpt 
